import { StyleSheet } from "react-native";
import { colors, spacing, font, radius } from "../Globaltheme";

export const styles = StyleSheet.create({
  scrollContent: { paddingBottom: spacing.xxxl + spacing.xl },
  header: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md },
  backButton: { color: colors.primary, fontSize: font.md, fontWeight: "600" },
  titleContainer: { paddingHorizontal: spacing.lg, marginBottom: spacing.lg },
  title: { fontSize: font.xxl, fontWeight: "800", color: colors.textPrimary },
  subtitle: {
    fontSize: font.sm,
    color: colors.textSecond,
    marginTop: spacing.xs,
  },
  section: { marginHorizontal: spacing.lg, marginBottom: spacing.md },
  fieldLabel: {
    fontSize: font.sm,
    fontWeight: "700",
    color: colors.textSecond,
    marginBottom: spacing.sm,
  },
  required: { color: colors.error },
  row: { flexDirection: "row", gap: spacing.md },
  halfField: { flex: 1 },

  dateButton: {
    height: 50,
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  dateButtonIcon: { fontSize: 16 },
  dateButtonText: {
    fontSize: font.md,
    color: colors.textPrimary,
    fontWeight: "600",
  },

  iosPickerContainer: {
    marginTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.md,
  },
  iosPickerClose: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
    marginTop: spacing.sm,
  },
  iosPickerCloseText: {
    color: colors.white,
    fontWeight: "700",
    fontSize: font.md,
  },

  input: {
    height: 50,
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    fontSize: font.md,
    color: colors.textPrimary,
  },
  inputError: { borderColor: colors.error, backgroundColor: colors.errorDim },
  errorText: { color: colors.error, fontSize: font.xs, marginTop: spacing.xs },
  textArea: { height: 100, paddingTop: spacing.md, textAlignVertical: "top" },
  charCount: {
    fontSize: font.xs,
    color: colors.textMuted,
    textAlign: "right",
    marginTop: spacing.xs,
  },

  typeGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  typeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  typeChipActive: {
    backgroundColor: colors.primaryDim,
    borderColor: colors.primary,
  },
  typeChipEmoji: { fontSize: 14 },
  typeChipText: {
    fontSize: font.sm,
    fontWeight: "600",
    color: colors.textSecond,
  },
  typeChipTextActive: { color: colors.primary },

  quantityRow: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "flex-start",
  },
  quantityInput: { flex: 1 },
  unitSelector: {
    height: 50,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minWidth: 95,
    justifyContent: "space-between",
  },
  unitSelectorText: {
    fontSize: font.sm,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  unitArrow: { fontSize: 10, color: colors.textMuted },
  unitDropdown: {
    position: "absolute",
    top: 54,
    right: 0,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 999,
    minWidth: 110,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  unitOption: { paddingVertical: spacing.md, paddingHorizontal: spacing.md },
  unitOptionActive: { backgroundColor: colors.primaryDim },
  unitOptionText: {
    fontSize: font.sm,
    color: colors.textPrimary,
    fontWeight: "500",
  },
  unitOptionTextActive: { color: colors.primary, fontWeight: "700" },

  saveButton: {
    backgroundColor: colors.primary,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.md,
    alignItems: "center",
  },
  saveButtonText: { color: colors.white, fontSize: font.md, fontWeight: "700" },
});
