version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tfg_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg_agricola
      MYSQL_USER: tfg_user
      MYSQL_PASSWORD: tfg_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
